org.gradle.jvmargs=-Xmx3G

minecraft_version=26.1.1
yarn_mappings=26.1.1+build.1
loader_version=0.16.2

fabric_version=0.105.0+26.1.1
fabric_kotlin_version=1.11.0+kotlin.2.0.0

sodium_version=mc26.1.1-0.6.0
lithium_version=mc26.1.1-0.14.0
ferritecore_version=7.1.0-fabric
appleskin_version=3.0.0+mc26.1.1
