$ErrorActionPreference = 'Stop'

$sourcePath = Join-Path $PSScriptRoot 'MainWindow.LoaderRuntime.cs'
if (-not (Test-Path $sourcePath)) {
    throw "MainWindow.LoaderRuntime.cs was not found."
}

$source = [System.IO.File]::ReadAllText($sourcePath)
$marker = '// TOPU FORGE MODULE PATH FIX'

if ($source.Contains($marker)) {
    Write-Host 'Forge launch fix already applied.'
    exit 0
}

$oldBlock = @'
                if (process == null)
                    throw new InvalidOperationException("CmlLib returned a null Minecraft process.");
'@

$newBlock = @'
                if (process == null)
                    throw new InvalidOperationException("CmlLib returned a null Minecraft process.");

                // TOPU FORGE MODULE PATH FIX
                // Forge 1.20.1's BootstrapLauncher is a Java module. CmlLib's
                // generated command can put the full library set on a normal
                // -cp before the Forge module-path command. Normalize it to the
                // command layout used by Forge's standard launcher.
                if (loaderType.Equals("Forge", StringComparison.OrdinalIgnoreCase))
                {
                    process.StartInfo.Arguments = NormalizeForgeProcessArguments(process.StartInfo.Arguments);
                    WriteLog("Applied Forge module-path launch normalization.");
                }
'@

if (-not $source.Contains($oldBlock)) {
    throw 'Could not find the Forge process insertion point.'
}
$source = $source.Replace($oldBlock, $newBlock)

$methodMarker = '        private Button? FindButtonByContent(Panel parent, string content)'
$method = @'
        private string NormalizeForgeProcessArguments(string arguments)
        {
            if (string.IsNullOrWhiteSpace(arguments))
                return arguments;

            // Remove the broad classpath generated by CmlLib for Forge. The
            // Forge 1.20.1 launcher's bootstrap libraries belong on the module
            // path and BootstrapLauncher is resolved from that module path.
            string normalized = System.Text.RegularExpressions.Regex.Replace(
                arguments,
                @"(?<!\S)-cp\s+(?:\"[^\"]*\"|\S+)",
                string.Empty,
                System.Text.RegularExpressions.RegexOptions.CultureInvariant);

            normalized = System.Text.RegularExpressions.Regex.Replace(
                normalized,
                @"(?<!\S)-p(?=\s)",
                "--module-path",
                System.Text.RegularExpressions.RegexOptions.CultureInvariant);

            return normalized.Trim();
        }

'@

if (-not $source.Contains($methodMarker)) {
    throw 'Could not find the Forge helper insertion point.'
}
$source = $source.Replace($methodMarker, $method + $methodMarker)

[System.IO.File]::WriteAllText($sourcePath, $source, [System.Text.UTF8Encoding]::new($false))
Write-Host 'Applied Forge module-path launch fix.'
